### 체크 예외와 인터페이스

이번에는 기존의 로직에서 다음 두 가지를 변경할 것이다.

- 체크 예외를 런타임 예외로 감싸서 예외에 대한 의존 제거하기
- Repository의 인터페이스를 만들어서, 서비스 단에서 구현 객체가 아닌 인터페이스에 의존하도록 변경

기존에 Repository를 인터페이스화 하지 못한 이유는, 체크 예외를 던지기 위해서는 인터페이스에서도 예외를 던져야 하기 때문이다.  
인터페이스에서 던지지 않은 예외를 구현 클래스에서 던지면 컴파일 에러가 발생한다.  

```java
public interface MemberRepositoryEx {
    Member save(Member member) throws SQLException;
    Member findById(String memberId) throws SQLException;
    void update(String memberId, int money) throws SQLException;
    void delete(String memberId) throws SQLException;
}
```

그렇다고 위와 같이 인터페이스에 예외를 명시하면 인터페이스가 특정 기술에 의존하게 된다.  
이러면 구현체를 유연하게 변경할 수 없어서 인터페이스를 사용하는 의미가 없어진다.

따라서 체크 예외를 런타임 예외로 감싸서, 인터페이스에는 예외를 명시하지 않아도 되게 만들어야 한다. 

```java
public interface MemberRepository {
    Member save(Member member);
    Member findById(String memberId);
    void update(String memberId, int money);
    void delete(String memberId);
}
```

### 런타임 예외 적용

위에서 정의한 체크 예외를 던지지 않는 Repository 인터페이스를 사용한다.  
SQLException을 감싸서 사용할 RuntimeException을 다음과 같이 정의한다.  

```java
public class MyDbException extends RuntimeException {
    public MyDbException() {}
    public MyDbException(String message) {
         super(message);
    }
    public MyDbException(String message, Throwable cause) {
        super(message, cause);
    }
    public MyDbException(Throwable cause) {
        super(cause);
    } 
}
```

이제 각 레포지토리 메서드의 catch 문에서 다음과 같이 에러를 감싸서 던지는 식으로 구현하면 된다.

```java
public class MemberRepositoryV4_1 implements MemberRepository {

    private final DataSource dataSource;

    public MemberRepositoryV4_1(DataSource dataSource) {
        this.dataSource = dataSource;
    }

    @Override
    public Member save(Member member) {
        String sql = "insert into member(member_id, money) values (?, ?)";

        Connection con = null;
        PreparedStatement pstmt = null;

        try {
            con = getConnection();
            pstmt = con.prepareStatement(sql);
            pstmt.setString(1, member.getMemberId());
            pstmt.setInt(2, member.getMoney());
            pstmt.executeUpdate();
            return member;
        } catch (SQLException e) {
            // 런타임 예외로 전환
            throw new MyDbException(e);
        } finally {
            close(con, pstmt, null);
        }

    }

    @Override
    public Member findById(String memberId) {
        String sql = "select * from member where member_id = ?";

        Connection con = null;
        PreparedStatement pstmt = null;
        ResultSet rs = null;

        try {
            con = getConnection();
            pstmt = con.prepareStatement(sql);
            pstmt.setString(1, memberId);

            rs = pstmt.executeQuery();
            if (rs.next()) {
                Member member = new Member();
                member.setMemberId(rs.getString("member_id"));
                member.setMoney(rs.getInt("money"));
                return member;
            } else {
                throw new NoSuchElementException("member not found memberId=" + memberId);
            }

        } catch (SQLException e) {
            // 런타임 예외로 전환
            throw new MyDbException(e);
        } finally {
            close(con, pstmt, rs);
        }
    }
}
```

이 때 이전 에러 원인을 로그로 남기기 위해 반드시 이전 에러를 감싸서 생성해야 한다.

이제 Repository단의 메서드에서 체크 예외가 발생하지 않으므로, 이들을 호출하는 Service 단에서도 더이상 체크 예외를 던지지 않아도 된다.  
Service 단에서 Repository 구현체 대신 인터페이스에 의존하도록 변경하고, 각 메서드의 체크 예외 정의 부분을 제거한다.

```java
public class MemberServiceV4 {

    // MemberRepository 인터페이스 사용
    private final MemberRepository memberRepository;

    public MemberServiceV4(MemberRepository memberRepository) {
        this.memberRepository = memberRepository;
    }

    @Transactional
    public void accountTransfer(String fromId, String toId, int money) {
        bizLogic(fromId, toId, money);
    }

    private void bizLogic(String fromId, String toId, int money) {
        Member fromMember = memberRepository.findById(fromId);
        Member toMember = memberRepository.findById(toId);

        memberRepository.update(fromId, fromMember.getMoney() - money);

        validation(toMember);
        memberRepository.update(toId, toMember.getMoney() + money);
    }

    private void validation(Member toMember) {
        if (toMember.getMemberId().equals("ex")) {
            throw new IllegalStateException("이체중 예외 발생");
        }
    }

}
```

이제 특정 기술에 의존하지 않도록 순수한 레포지토리 인터페이스와 서비스 계층을 만들 수 있었다.  
따라서 jdbc가 아닌 다른 db 기술을 사용하더라도 유연하게 구현체를 갈아끼울 수 있다.  

다만 현재는 모든 예외를 MyDBException으로 감싸서 던지기 때문에, 클라이언트 단에서 예외를 구분해서 처리할 수 없다는 문제가 있다.  
sql문이 잘못 되었거나 인덱스가 잘못 걸려 있는 등 복구가 가능한 오류 상황에서는 복구하도록 로직을 구성하고 싶으면 어떻게 해야 할까?

### 데이터 접근 예외 직접 만들기

예외를 일괄적으로 처리하는 것이 아니라, 일부의 조건에서는 별도의 복구 로직을 거치도록 구성하고 싶을 수 있다.  
예를 들어 키 중복 오류가 발생했을 때, 별도의 랜덤 스트링을 붙여서 유니크 키를 만드는 식으로 복구 로직을 구성할 수 있다.

이 때에는 레포지토리 단에서 SQLException을 catch할 때 errorCode를 확인해서 어떤 예외가 발생했는지 확인하고, 이에 맞게 다른 로직이 실행되도록 해야 한다.  
각 db 구현 기술에서는 중복키, SQL 문법 오류 등 다양한 상황에 대한 에러 코드를 미리 정의해두었다.

```java
e.getErrorCode() == 23505
```

각 오류 상황에 맞게 복구를 수행하는 로직은 서비스단에 들어가야 한다.  
이를 위해서는 각 errorCode 별로 다른 처리를 해야 하는데, 서비스 단에서 getErrorCode 메서드 호출을 위해 SQLException을 직접 참조하면 서비스 계층의 순수성이 깨진다.  

```java
((SQLException) e.getCause()).getErrorCode()
```

따라서 각 에러 상황에 해당하는 별도의 커스텀 예외를 정의하고, 레포지토리 단에서 에러 코드를 확인해서 적절한 커스텀 예외를 던지도록 해야 한다.  
이 때 서비스 단에서는 예외 클래스를 바탕으로 에러 상황을 구분하게 된다.

먼저 기존에 정의했던 MyDbException을 상속한 MyDuplicateKeyException을 정의한다.

```java
public class MyDuplicateKeyException extends MyDbException {
    public MyDuplicateKeyException() {
    }
    public MyDuplicateKeyException(String message) {
        super(message);
    }
    public MyDuplicateKeyException(String message, Throwable cause) {
        super(message, cause);
    }
    public MyDuplicateKeyException(Throwable cause) {
        super(cause);
    } 
}
```

이제 레포지토리 단에서 errorCode를 바탕으로 적절한 커스텀 예외를 던지도록 구현하면 된다.

```java
public class ExTranslatorV1Test {

    Repository repository;
    Service service;

    @BeforeEach
    void init() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource(URL, USERNAME, PASSWORD);
        repository = new Repository(dataSource);
        service = new Service(repository);
    }

    @Test
    void duplicateKeySave() {
        service.create("myId");
        service.create("myId");//같은 ID 저장 시도
    }

    @Slf4j
    @RequiredArgsConstructor
    static class Service {
        private final Repository repository;

        public void create(String memberId) {
            try {
                repository.save(new Member(memberId, 0));
                log.info("saveId={}", memberId);
            // 각 errorCode에 대한 예외 클래스 별 따른 처리
            } catch (MyDuplicateKeyException e) {
                log.info("키 중복, 복구 시도");
                String retryId = generateNewId(memberId);
                log.info("retryId={}", retryId);
                repository.save(new Member(retryId, 0));
            } catch (MyDbException e) {
                log.info("데이터 접근 계층 예외", e);
                throw e;
            }
        }

        private String generateNewId(String memberId) {
            return memberId + new Random().nextInt(10000);
        }

    }

    @RequiredArgsConstructor
    static class Repository {
        private final DataSource dataSource;

        public Member save(Member member) {
            String sql = "insert into member(member_id, money) values(?,?)";
            Connection con = null;
            PreparedStatement pstmt = null;

            try {
                con = dataSource.getConnection();
                pstmt = con.prepareStatement(sql);
                pstmt.setString(1, member.getMemberId());
                pstmt.setInt(2, member.getMoney());
                pstmt.executeUpdate();
                return member;
            } catch (SQLException e) {
                // 에러 코드 확인, 적절한 커스텀 예외로 감싸기
                if (e.getErrorCode() == 23505) {
                    throw new MyDuplicateKeyException(e);
                }
                throw new MyDbException(e);
            } finally {
                JdbcUtils.closeStatement(pstmt);
                JdbcUtils.closeConnection(con);
            }
        }
    }
}
```

h2 db에서는 중복키 오류가 발생했을 때 에러 코드가 23505이다.  
해당 오류 코드에서는 MyDuplicateKeyException으로 감싸서 던지고, 그 외의 상황에서는 MyDbException으로 감싸서 던지도록 구성했다.

이제 서비스 계층에서는 catch에서 에러를 잡을 때 에러 종류 별로 복구 로직을 수행하게 된다.  
서비스 단에서는 기술에 의존하지 않는 커스텀 예외에만 의존한다.
MyDuplicateKeyException이 발생한 경우에는 generateNewId()로 새로운 id를 생성하여 복구 로직을 실행하도록 하고, 다른 일반적인 MyDbException 예외에 대해서는 그냥 로그를 남기고 던지도록 했다.  

복구 로직이 수행됨에 따라 다음의 로그를 확인할 수 있다.  

```
Service - saveId=myId
Service - 키 중복, 복구 시도 
Service - retryId=myId492
```

이제 에러 코드에 맞게 적절한 커스텀 예외가 발생하여, 서비스 단에는 순수성을 유지란 채로 예외에 대한 복구 로직을 둘 수 있었다.  
다만 각 db 기술마다 정의된 에러 코드가 다르고 수백가지 상황에 대한 에러 코드를 각각 정의해 두었기 때문에, 이를 모두 고려하여 예외를 구성하기는 매우 번거롭다.  

### 스프링 예외 추상화 이해

스프링에서는 데이터 접근과 관련된 예외들을 추상화하여 계층적으로 제공한다.  
각 에러 상황에 대해 추상화된 예외들이 존재하고, db 기술이 mysql이든 h2든 관계없이, 또 접근 기술이 JDBC든 JPA든 관계 없이, 발생한 문제에 맞는 일관된 예외를 반환해준다.

데이터 접근 관련 에러들의 가장 상위에는 DataAccessException이 있다.  
해당 예외는 RuntimeException을 상속하기 때문에, 데이터 접근 관련 예외는 모두 런타임 예외이다.  
하위에는 크게 두 종류의 예외가 자식으로 존재하는데, Transient 예외와 NonTransient 예외로 나뉜다.  

Transient 예외는 해당 sql을 다시 수행하면 에러가 발생하지 않을 수도 있는 경우에 발생한다.  
대표적으로 쿼리 타임아웃 이나 락과 관련된 예외들이 있다.  

NonTransient는 반복 수행해도 반드시 오류가 발생하는 예외이다.  
sql 문법 오류, 데이터베이스 제약 조건 위반 등의 상황에서 발생한다.

만약 에러 코드를 기반으로 스프링의 계층화된 예외를 직접 던지려면 다음과 같이 errorCode를 확인해서 던지는 코드를 작성해야 한다.

문제는 각 db마다 에러 코드도 다르고,그 에러 종류도 수백가지라는 점이다.

    @Test
    void sqlExceptionErrorCode() {
        String sql = "select bad grammar";
        try {
            Connection con = dataSource.getConnection();
            PreparedStatement stmt = con.prepareStatement(sql);
            stmt.executeQuery();
        } catch (SQLException e) {
            assertThat(e.getErrorCode()).isEqualTo(42122);
            int errorCode = e.getErrorCode();
            log.info("errorCode={}", errorCode);
            //org.h2.jdbc.JdbcSQLSyntaxErrorException
            log.info("error", e);
      } 
}
스프링에서는 데이터베이스에서 발생한 예외를 스프링이 정의한 예외로 변환해주는 변환기를 제공한다

이를 이용하면 간편하게 스프링의 계층화된 예외로 변환할 수 있다

  @Test
  void exceptionTranslator() {
      String sql = "select bad grammar";
      try {
          Connection con = dataSource.getConnection();
          PreparedStatement stmt = con.prepareStatement(sql);
          stmt.executeQuery();
      } catch (SQLException e) {
          assertThat(e.getErrorCode()).isEqualTo(42122);
          //org.springframework.jdbc.support.sql-error-codes.xml
          SQLExceptionTranslator exTranslator = new
  SQLErrorCodeSQLExceptionTranslator(dataSource);
e);
//org.springframework.jdbc.BadSqlGrammarException
DataAccessException resultEx = exTranslator.translate("select", sql,
log.info("resultEx", resultEx);
  assertThat(resultEx.getClass()).isEqualTo(BadSqlGrammarException.class);
      }
  }
 위 예시에서는 sql 문법이 잘못 되었으므로 BadSqlGrammarException 예외로 변환된다.

해당 변환기에서는 sql-error-codes.xml 파일을 참조해서 예외 종류를 판단한다.  
해당 파일에는 각 db 종류에 따라 각 예외에 해당하는 에러 코드가 정리되어 있다.

이와 같이 스프링의 데이터 접근 예외 계층을 사용하면 서비스 단에서도 스프링 기술에 의존적이게 된다는 단점이 있다.  
하지만 이로 인해 얻는 효용이 크기 때문에, 해당 부분은 스프링 기술에 의존하는 것이 적절하다.




